### ISSUE TITLE
SSLError message

### ISSUE THREAD

**Issue by Pooski** [HOWZ1T/py_proxy#5] opened 2019-01-18 20:01 UTC
Copied and pasted the example code after installing the library. I receive this error message whenever I run the code:

SSLError: HTTPSConnectionPool(host='free-proxy-list.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))

**Comment by HOWZ1T** [comment] 2019-01-28 02:17
Hi Pooski, thanks for opening the issue.

Unfortunately, I am unable to reproduce the error. I will be closing this issue, as the error is not a fault of the library itself but some other external factors: such as hardware, internet connection etc.

From your error log it seems like it could be a network issue, particularly with the SSL connection with the host (in this case: 'free-proxy-list.net'). It seems that it couldn't verify the ssl certificate for the proxy listing website.

All the best,
Dylan

**Closed as completed by HOWZ1T** 2019-01-28 02:17 UTC
