### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Sergeydigl3** [HOWZ1T/py_proxy#1] opened 2018-07-23 14:37 UTC
0 proxies

**Comment by HOWZ1T** [comment] 2018-07-23 14:40
Hi, could you be more specific ?
If you are filtering proxies by country, try another country or remove the filter.

**Comment by HOWZ1T** [comment] 2018-07-23 15:14
After some further investigation, it appears that their is an issue with getting the proxies.
I will look into resolving this issue.

**Comment by HOWZ1T** [comment] 2018-07-29 09:12
The issue is resolved.

**Closed as completed by HOWZ1T** 2018-07-29 09:12 UTC
Labels: bug
